SELECT
	P.IDPED				AS InternalId 
    ,P.CORRCLI
    ,C.CODCLIENTESONEPAR AS CardCode
    ,S.SERIES_PROY 		AS Project
    ,S.SERIES 	 		AS Series
    ,P.NROPEDIDO 		AS U_EXX_NRODEPDE
    ,U.USUARIO
    ,P.FECHAPEDIDO 		AS DocDate
	,P.MONEDA 			AS DocCurrency
    ,P.CODCONDPAGO 		AS PaymentGroupCode
	,U.CODVENDEDORSAP	AS SalesPersonCode
    ,P.DIRENTREGA
    ,P.VERSIONAPP			
    ,PD.CORRPROD 		AS ItemCode
    ,PD.CANTIDAD 		AS Quantity
    ,PD.PRECIO 			AS UnitPrice
    ,''					AS Comments
    
FROM TSONEPARPEDIDOS P 
INNER JOIN TSONEPARPEDIDOSDETALLE PD ON
P.IDPED = PD.IDPED
INNER JOIN TSONEPARCLIENTES C ON
C.CORRCLIENTE = P.CORRCLI
INNER JOIN TSONEPARCLIENTES_USUARIOS U ON
U.USUARIO = P.USUARIO
INNER JOIN TSONEPARSUCURSALES S ON
S.CODSONEPAR = C.CODSONEPAR
WHERE P.ACTIVO = 1