//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SONEPAR.SAPMIGRATION.WSS.MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_SAPMIGRATIONEntities : DbContext
    {
        public DB_SAPMIGRATIONEntities()
            : base("name=DB_SAPMIGRATIONEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MigrationDocument> MigrationDocument { get; set; }
        public virtual DbSet<MigrationDocumentLine> MigrationDocumentLine { get; set; }
    }
}
