//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SONEPAR.SAPMIGRATION.WSS.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MigrationDocumentLine
    {
        public int C_MigrationDocumentLineId { get; set; }
        public string C_ExternalId { get; set; }
        public string C_ParentExternalId { get; set; }
        public Nullable<int> LineNum { get; set; }
        public Nullable<int> SalesPersonCode { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> DiscountPercent { get; set; }
        public string WarehouseCode { get; set; }
        public string TaxCode { get; set; }
        public string Currency { get; set; }
        public string ProjectCode { get; set; }
        public string ShipToDescription { get; set; }
        public Nullable<double> DisccountPercent { get; set; }
        public Nullable<double> LineTotal { get; set; }
        public Nullable<double> U_RX_STKDIS { get; set; }
        public Nullable<double> U_RX_STKRSV { get; set; }
        public Nullable<double> U_RX_STOKCD { get; set; }
        public string U_RX_PRIADD { get; set; }
        public string U_RX_DSCADD { get; set; }
        public string U_EXX_FE_TPVU { get; set; }
        public string U_EXX_FE_TAIGV { get; set; }
        public string U_RX_MARCA { get; set; }
        public string U_RX_ACCPED { get; set; }
    }
}
