//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SONEPAR.SAPMIGRATION.WSS.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MigrationDocument
    {
        public int C_MigrationDocumentId { get; set; }
        public string C_ExternalId { get; set; }
        public int DocObjectCode { get; set; }
        public Nullable<int> ObjectType { get; set; }
        public Nullable<int> DocumentSubType { get; set; }
        public Nullable<int> DocNum { get; set; }
        public Nullable<int> Series { get; set; }
        public string CardCode { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<System.DateTime> DocDueDate { get; set; }
        public Nullable<System.DateTime> TaxDate { get; set; }
        public int DocType { get; set; }
        public string DocCurrency { get; set; }
        public string Comments { get; set; }
        public Nullable<int> PaymentGroupCode { get; set; }
        public Nullable<int> SalesPersonCode { get; set; }
        public string Project { get; set; }
        public string Indicator { get; set; }
        public string ShipToCode { get; set; }
        public string Address2 { get; set; }
        public Nullable<int> DocumentsOwner { get; set; }
        public string AgentCode { get; set; }
        public Nullable<int> TransportationCode { get; set; }
        public string NumAtCard { get; set; }
        public Nullable<int> ContactPersonCode { get; set; }
        public Nullable<int> DocEntry { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string U_RX_ORIREQ { get; set; }
        public string U_EXX_NRODEPDE { get; set; }
        public string C_DestinationSapDb { get; set; }
        public int C_AppSource { get; set; }
        public bool C_IsUpdate { get; set; }
        public Nullable<bool> C_SaveAsDraft { get; set; }
        public Nullable<int> C_MigrationState { get; set; }
        public Nullable<System.DateTime> C_MigrationDate { get; set; }
        public Nullable<int> C_MigrationErrorType { get; set; }
        public string C_MigrationErrorMessage { get; set; }
        public string C_MigrationMailContentBody { get; set; }
        public Nullable<bool> C_MigrationMailWasSended { get; set; }
        public Nullable<System.DateTime> C_MigrationMailDate { get; set; }
        public string C_MigrationObs { get; set; }
    }
}
