//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SONEPAR.SAPMIGRATION.WSS.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSLP
    {
        public int SlpCode { get; set; }
        public string SlpName { get; set; }
        public string Memo { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<short> GroupCode { get; set; }
        public string Locked { get; set; }
        public string DataSource { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string Active { get; set; }
        public string Telephone { get; set; }
        public string Mobil { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string U_RX_NOMEMP { get; set; }
        public string U_RX_TLFEMP { get; set; }
        public string U_RX_ANXEMP { get; set; }
        public string U_RX_EMLEMP { get; set; }
        public string U_RX_JEFEMP { get; set; }
        public string U_RX_SUCURS { get; set; }
    }
}
