//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SONEPAR.SAPMIGRATION.WSS.MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SAPModelEntities : DbContext
    {
        public SAPModelEntities()
            : base("name=SAPModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OCRD> OCRD { get; set; }
        public virtual DbSet<OSLP> OSLP { get; set; }
        public virtual DbSet<ORDR> ORDR { get; set; }
        public virtual DbSet<OCPR> OCPR { get; set; }
        public virtual DbSet<OHEM> OHEM { get; set; }
        public virtual DbSet<OITW> OITW { get; set; }
        public virtual DbSet<RDR1> RDR1 { get; set; }
        public virtual DbSet<OITM> OITM { get; set; }
        public virtual DbSet<OPRJ> OPRJ { get; set; }
    }
}
